export const INDIAN_LANGUAGES = [
  { code: "en",  name: "English",    native: "English"       },
  { code: "hi",  name: "Hindi",      native: "हिन्दी"         },
  { code: "bn",  name: "Bengali",    native: "বাংলা"          },
  { code: "te",  name: "Telugu",     native: "తెలుగు"         },
  { code: "mr",  name: "Marathi",    native: "मराठी"          },
  { code: "ta",  name: "Tamil",      native: "தமிழ்"          },
  { code: "ur",  name: "Urdu",       native: "اردو"           },
  { code: "gu",  name: "Gujarati",   native: "ગુજરાતી"        },
  { code: "kn",  name: "Kannada",    native: "ಕನ್ನಡ"          },
  { code: "or",  name: "Odia",       native: "ଓଡ଼ିଆ"          },
  { code: "ml",  name: "Malayalam",  native: "മലയാളം"         },
  { code: "pa",  name: "Punjabi",    native: "ਪੰਜਾਬੀ"         },
  { code: "as",  name: "Assamese",   native: "অসমীয়া"        },
  { code: "ne",  name: "Nepali",     native: "नेपाली"         },
  { code: "sa",  name: "Sanskrit",   native: "संस्कृतम्"      },
  { code: "ks",  name: "Kashmiri",   native: "کٲشُر"          },
  { code: "sd",  name: "Sindhi",     native: "سنڌي"           },
  { code: "mai", name: "Maithili",   native: "मैथिली"         },
  { code: "kok", name: "Konkani",    native: "कोंकणी"         },
  { code: "mni", name: "Manipuri",   native: "মেইতেই লোন্"    },
  { code: "doi", name: "Dogri",      native: "डोगरी"          },
  { code: "brx", name: "Bodo",       native: "बड़ो"           },
];

export const UI_STRINGS = {
  // Publish form
  next: "Next",
  submitRating: "Submit Rating",
  typeAnswer: "Type your answer...",
  submitting: "Submitting...",
  formSubmitted: "Form submitted successfully!",
  loadingForm: "Loading form...",
  translating: "Translating...",
  fillOutField: "Please fill out this field",
  errorSubmittingForm: "Failed to submit form. Please try again.",

  // Navbar
  light: "Light",
  dark: "Dark",
  share: "Share",
  copied: "Copied!",
  save: "Save",
  saving: "Saving...",
  flow: "Flow",
  responses: "Responses",
  settingsMenu: "Settings",
  logout: "Logout",

  // Login
  fillInAllFields: "Please fill in all fields",
  loginFailed: "Login failed. Please try again.",
  welcomeBack: "Welcome back",
  signInToContinue: "Sign in to continue building forms",
  emailLabel: "Email",
  passwordLabel: "Password",
  enterEmail: "Enter your email",
  logIn: "Log in",
  loggingIn: "Logging in...",
  orDivider: "or",
  continueWithGoogle: "Continue with Google",
  noAccount: "Don't have an account?",
  registerNow: "Register now",

  // Register
  createYourAccount: "Create your account",
  startBuilding: "Start building conversational forms",
  usernameLabel: "Username",
  enterUsername: "Enter your username",
  confirmPasswordLabel: "Confirm Password",
  register: "Register",
  registering: "Registering...",
  alreadyHaveAccount: "Already have an account?",
  loginLink: "Login",

  // Forms page
  myForms: "My Forms",
  createForm: "Create Form",
  newFolder: "New Folder",
  noForms: "No forms yet. Create your first form!",
  deleteLabel: "Delete",
  shareForm: "Share",
  viewResponses: "Responses",
  dropHere: "Drop here",
  loadingForms: "Loading your forms...",
  folderNamePlaceholder: "Folder name",
  creating: "Creating...",
  create: "Create",
  cancel: "Cancel",
  errorLoadingForms: "Failed to load your forms. Please refresh the page.",
  errorCreatingFolder: "Error creating folder",
  errorDeletingFolder: "Error deleting folder",
  errorDeletingForm: "Error deleting form",
  errorMovingForm: "Failed to move form into folder",

  // FormBuilder
  errorSavingForm: "Error saving form",
  errorCopyingLink: "Failed to copy form link",
  formNamePlaceholder: "Form Name",
  untitledForm: "Untitled Form",
  yourForms: "Your Forms",
  yourFolders: "Your Folders",
  dragFormHint: "drag a form onto a folder to move it",
  bubblesSection: "BUBBLES",
  inputsSection: "INPUTS",
  textField: "Text",
  imageField: "Image",
  videoField: "Video",
  gifField: "GIF",
  numberField: "Number",
  phoneField: "Phone",
  dateField: "Date",
  ratingField: "Rating",
  buttonsField: "Buttons",
  noFieldsAdded: "No fields added yet. Use sidebar to add fields.",
  fieldLabelPlaceholder: "Field label",
  placeholderText: "Placeholder text...",
  maxStars: "Max stars",
  addOption: "+ Add",
  typeBubbleMessage: "Type bubble message...",
  statesTitle: "States",
  classicTheme: "Classic",
  warmTheme: "Warm",
  minimalTheme: "Minimal",

  // Settings
  settingsTitle: "Settings",
  profileSection: "Profile",
  nameLabel: "Name",
  saveChanges: "Save Changes",
  changePasswordSection: "Change Password",
  currentPassword: "Current Password",
  newPassword: "New Password",

  // Response page
  viewsLabel: "Views",
  startsLabel: "Starts",
  completionRateLabel: "Completion Rate",
  noResponsesYet: "No responses yet.",
  submittedAt: "Submitted at",
};
